all: true
check-coverage: true
include:
  - "src/**/*.js"
exclude:
  - "src/assets/*"
  - "**/*.test.js"
  - "src/dynamo-session-config.js"
  - "**/*router.js"
  - "src/app.js"
  - "src/lib/*"
  - "src/app/shared/oauth.js"
  - "src/app/drivingLicence/router.js"
  - "src/app/drivingLicence/steps.js"
  - "src/app/drivingLicence/fields.js"

report-dir: reports/coverage
statements: 60
branches: 60
functions: 80
lines: 60
watermarks:
  statements:
    - 80
    - 90
  branches:
    - 80
    - 90
  functions:
    - 80
    - 90
  lines:
    - 80
    - 90
